[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
KomaMRI = "6a340f8b-2cdf-4c04-99be-4953d9b66d0a"
KomaMRIBase = "d0bc0b20-b151-4d03-b2a4-6ca51751cb9c"
KomaMRICore = "4baa4f4d-2ae9-40db-8331-a7d1080e3f4e"
KomaMRIFiles = "fcf631a6-1c7e-4e88-9e64-b8888386d9dc"
KomaMRIPlots = "76db0263-63f3-4d26-bb9a-5dba378db904"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"

[sources]
KomaMRI = {rev = "fast-gpu", url = "https://github.com/JuliaHealth/KomaMRI.jl"}
KomaMRIBase = {rev = "fast-gpu", subdir = "KomaMRIBase", url = "https://github.com/JuliaHealth/KomaMRI.jl"}
KomaMRICore = {rev = "fast-gpu", subdir = "KomaMRICore", url = "https://github.com/JuliaHealth/KomaMRI.jl"}
KomaMRIPlots = {rev = "fast-gpu", subdir = "KomaMRIPlots", url = "https://github.com/JuliaHealth/KomaMRI.jl"}
KomaMRIFiles = {rev = "fast-gpu", subdir = "KomaMRIFiles", url = "https://github.com/JuliaHealth/KomaMRI.jl"}